config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'
  get 'revenues_controller/index'
  get 'messages/index'
  get 'conversations/index'
  root 'homes#top'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, except: [:edit]  do
    member do
      get 'profile'
      get 'description'
      get 'favorite_store'
      get 'photo_upload'
      get 'exit'
    end
  end

  resources :plans, except: [:edit] do
    member do
      get 'listing'
      get 'rest_info'
      get 'description'
      get 'photo_upload'
      get 'time_info'
    end
    resources :photos, only: [:update, :destroy]
    resources :reservations, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/your_reservation' => 'reservations#your_reservation'
  get '/your_entry' => 'reservations#your_entry'

  resources :restaurants, only: [:create, :update]
  get '/search_gnabi' => 'restaurants#search_gnabi'

  get 'search' => 'homes#search'
  get 'search_jenre' => 'homes#search_jenre'

  get 'dashboard' => 'dashboards#index'
  resources :revenues, only: [:index]

  get '/payment_method' => "users#payment"
  post '/add_card' => "users#add_card"

  post 'messages' => 'messages#create'
  get '/conversations' => 'conversations#list'
  get '/conversations/:id' => 'conversations#show', as: "conversation_detail"

  get '/about' => "homes#about"
  get '/privacy' => "homes#privacy"
  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  attachment :image

  has_many :plans, dependent: :destroy
  has_many :restaurants, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :guest_reviews, class_name: 'GuestReview', foreign_key: 'guest_id'
  has_many :host_reviews, class_name: 'HostReview', foreign_key: 'host_id'
  has_many :notifications

  belongs_to :jenre, optional: true

  enum sex: { 男性: 0, 女性: 1 }

  validates :fullname, presence: true, length: { maximum: 30 }

  # omniauthのコールバック時に呼ばれる
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.fullname = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # プロフィールの項目が入力されているか確認する
  def is_ready_user?
    !active && fullname.present? && email.present? && description.present? && image_id.present? && favorite_store.present? && jenre_id.present?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # callback for facebook
  def facebook
    callback_for(:facebook)
  end

  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: provider.to_s.capitalize)
      end
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: %i[payment add_card]
  before_action :authenticate_user!, except: [:show]
  before_action :forbid_test_user, only: %i[update exit destroy]
  before_action :ensure_correct_user, only: %i[profile description photo_upload favorite_store update destroy]

  def show
    @plans = @user.plans
    @guest_reviews = Review.where(type: 'GuestReview', host_id: @user.id).page(params[:page]).per(4)
    @host_reviews = Review.where(type: 'HostReview', guest_id: @user.id).page(params[:page]).per(4)
  end

  def update
    new_params = user_params
    new_params = user_params.merge(active: true) if @user.is_ready_user?

    if @user.update(new_params)
      if @user.active == true
        return redirect_to user_path(@user), notice: 'プロフィールを公開しました！'
      end

      flash[:notice] = '編集内容を保存しました！'
    else
      flash[:alert] = '編集内容の保存に失敗しました...'
    end
    redirect_back(fallback_location: request.referer)
  end

  def add_card
    if current_user.stripe_id.blank?
      customer = Stripe::Customer.create(
        email: current_user.email,
        description: 'BistMatch 有料プランご利用'
      )
      current_user.stripe_id = customer.id
      current_user.save

      # クレカ情報をStripeに追加する
      customer.sources.create(source: params[:stripeToken])
    else
      customer = Stripe::Customer.retrieve(current_user.stripe_id)
      customer.source = params[:stripeToken]
      customer.save
    end

    flash[:notice] = 'カード情報を保存しました！'
    redirect_to payment_method_path
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to payment_method_path
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: '退会処理が完了しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  # 正しいユーザーか確認する
  def ensure_correct_user
    unless current_user.id == @user.id
      redirect_to root_path, alert: '権限がありません..'
      end
  end

  def user_params
    params.require(:user).permit(:fullname, :email, :phone_number, :description, :image, :sex, :age,
                                 :favorite_store, :job, :jenre_id, :active)
  end

  def forbid_test_user
    if @user.email == 'testuser@gmail.com'
      flash[:alert] = 'テストユーザーのため変更できません'
      redirect_back(fallback_location: request.referer)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_menu.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    登録必須項目
  </div>

  <div class="panel-body">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "プロフィール", profile_user_path, class: "sidebar-link active" %>
        <% if !@user.fullname.blank? && !@user.email.blank? %>
        <span class="pull-right text-babu"><i class="fas fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "自己紹介", description_user_path, class: "sidebar-link active" %>
        <% if !@user.description.blank? %>
          <span class="pull-right text-babu"><i class="fas fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "画像アップロード", photo_upload_user_path, class: "sidebar-link active" %>
        <% if !@user.image_id.blank? %>
          <span id="photo_check" class="pull-right text-babu"><i class="fas fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "お気に入り", favorite_store_user_path, class: "sidebar-link active" %>
        <% if !@user.favorite_store.blank? && !@user.jenre_id.blank? %>
          <span class="pull-right text-babu"><i class="fas fa-check"></i></span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<hr/>


<% if @user.active == false %>
  <%= form_for @user do |f| %>
    <%= f.hidden_field :active, value: true %>
    <%= f.submit "プロフィールを公開する", id: "publish_button", class: "btn btn-normal btn-block" %>
  <% end %>
<% else %>
  <%= link_to "マイページへ行く", user_path(current_user), class: 'btn btn-normal' %>
<% end %>

app/views/users/description.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          自己紹介
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @user do |f| %>

              <div class="row">
                <div class="form-group">
                  <label>自己紹介コメント</label>
                  <%= f.text_area :description, rows: 7,  placeholder: "プロフィールに載せる自己紹介コメントを入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "保存", class: "btn btn-form" %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/exit.html.erb
<div class="container row-space-5 text-center">
  <h2>退会ページ</h2>
  <div class="row text-center">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">退会確認</div>
        <div class="panel-body">
          <div class="row">
            <h4>本当に退会しますか？</h4>
            <div class="col-md-6">
              <%= link_to 'マイページへ', user_path(current_user), class: 'btn btn-block btn-form' %>
            </div>
            <div class="col-md-6">
              <%= link_to "退会する", user_path(current_user),class: 'btn btn-block btn-normal', method: :delete, "data-confirm" => "本当に退会しますか？" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/favorite_store.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          お気に入り
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @user do |f| %>

              <div class="row">
                  <div class="form-group">
                    <label>好きな飲食店のジャンル</label>
                    <%= f.collection_select :jenre_id, Jenre.all, :id, :name, :prompt => "選択して下さい", class: 'form-control' %>
                  </div>
                </div>


                <div class="row">
                  <div class="form-group">
                    <label>好きなお店</label>
                    <%= f.text_field :favorite_store, placeholder: "一番好きなお店を入力...", class: "form-control", required: true %>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "保存", class: "btn btn-form" %>
                </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/payment.html.erb
<div class="container row-space-5">
  <div class="row">
    <div class="col-md-3">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "支払い情報登録", payment_method_path, class: "sidebar-link active" %></li>
        <li class="sidebar-item"><%= link_to "通知設定", payment_method_path, class: "sidebar-link" %></li>
      </ul>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">カード情報の登録</div>
        <div class="panel-body">
          <div class="container">
             <%= form_tag("/add_card", method: "post", id: "add-card") do %>

                <label>
                  <span>Name</span>
                  <input name="cardholder-name" class="field" placeholder="Ichiro Suzuki" />
                </label>

                <label>
                  <span>Card</span>
                  <div id="card-element" class="field"></div>
                </label>

                <div class="outcome">
                  <div class="error" role="alert"></div>
                </div>

                <% if current_user.stripe_id %>
                  <button type="submit" class="btn btn-normal btn-block">カード情報の更新</button>
                <% else %>
                  <button type="submit" class="btn btn-normal btn-block">カード情報の追加</button>
                <% end %>


            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
  $(function() {

    var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
    var elements = stripe.elements();

    var card = elements.create('card', {
      hidePostalCode: true,
      style: {
        base: {
          iconColor: '#F99A52',
          color: '#32315E',
          lineHeight: '48px',
          fontWeight: 400,
          fontFamily: '"Helvetica Neue", "Helvetica", sans-serif',
          fontSize: '15px',

          '::placeholder': {
            color: '#CFD7DF',
          }
        },
      }
    });

    card.mount('#card-element');

    function setOutcome(result) {

      var errorElement = document.querySelector('.error');
      errorElement.classList.remove('visible');

      if (result.token) {
        var form = $('#add-card');
        form.append($('<input type="hidden" name="stripeToken">').val(result.token.id));
        form.get(0).submit();
      } else if (result.error) {
        errorElement.textContent = result.error.message;
        errorElement.classList.add('visible');
      }
    }

    card.on('change', function(event) {
      setOutcome(event);
    });

    $('#add-card').on('submit', function(e) {
      e.preventDefault();
      var extraDetails = {
        name: $('input[name=cardholder-name]').value
      };
      stripe.createToken(card, extraDetails).then(setOutcome);
    });

  });
</script>

app/views/users/photo_upload.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          Photos
        </div>

        <div class="panel-body">
          <div class="container">
            <div class="row">
              <div class="col-md-offset-3 col-md-6">
                <!-- PHOTOS UPLOAD GOES HERE -->

                <%= form_for @user do |f| %>
                  <div class="row">
                    <div class="form-group">
                      <span class="btn btn-default btn-file text-babu">
                        <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i> 画像を選ぶ
                        <%= f.attachment_field :image, placeholder: "プロフィール画像", id: 'user_img' %>
                      </span>
                    </div>
                  </div>

                  <div class="text-center">
                    <%= f.submit "選択した画像に変更する", class: "btn btn-form" %>
                  </div>

                <% end %>
              </div>
            </div>

            <div id="photo"><%= render 'photos/photos_prev' %></div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          プロフィール
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @user do |f| %>

              <div class="row">
                <div class="form-group">
                  <label>名前（フルネーム）</label>
                  <%= f.text_field :fullname, placeholder: "鈴木 一郎 または Ichiro Suzuki...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>メールアドレス</label>
                  <%= f.text_field :email, placeholder: "メールアドレスを入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>電話番号</label>
                  <%= f.text_field :phone_number, placeholder: "電話番号をを入力(ハイフンなし)...", class: "form-control", required: true %>
                </div>
              </div>


              <div class="row">
                <div class="form-group">
                  <label>性別</label>
                  <%= f.select :sex, User.sexes.keys.to_a, {}, class: "form-control", required: true %>
                </div>
              </div>


              <div class="row">
                <div class="form-group">
                  <label>年齢</label>
                  <%= f.text_field :age, placeholder: "年齢を入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>職業</label>
                  <%= f.text_field :job, placeholder: "職業を入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "保存", class: "btn btn-form" %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><%= @user.fullname %> 様</div>
        <div class="panel-body">
          <div class="image-wrapper">
            <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "no_image.png", size:'100x100', class: "img-circle" %><br/><br/>
          </div>
          <ul class="sidebar-list user-info">
            <li>E-mail: <span class="pull-right icon-babu"><i class="fas fa-envelope"></i></span><%= @user.email %></li>
            <li>職業: <span class="pull-right icon-babu"><i class="fas fa-user-md"></i></span><%= @user.job %></li>
            <li>好きなジャンル: <span class="pull-right icon-babu"><i class="fas fa-utensils"></i></span><%= @user.jenre.name %></li>
            <li>好きなお店: <span class="pull-right icon-babu"><i class="fas fa-utensils"></i></span><%= @user.favorite_store %></li><br>
            <% if current_user && current_user != @user %>
              <li><%= render partial: "messages/message_form", locals: {user: @user} %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading"><%= @user.fullname %></div>
        <div class="panel-body">
          <div class="description row-space-3">
            <%= @user.description %>
          </div>
        </div>
      </div>

      <h4>ホストプラン一覧 (<%= @plans.length %>)</h4><br/>

      <div class="row">
        <%= render partial: "plans/plan_list", locals: {plans: @plans} %>
      </div>
      <br/>

      <div class="panel panel-default">
        <div class="panel-heading">ゲストからのレビュー (<%= @guest_reviews.count %>)</div>
        <div class="panel-body">
          <div class="row">
            <%= render "reviews/guest_list" %>
          </div>
        </div>
      </div>
      <br/>

      <div class="panel panel-default">
        <div class="panel-heading">ホストからのレビュー (<%= @host_reviews.count %>)</div>
        <div class="panel-body">
          <div class="row">
            <%= render "reviews/host_list" %>
          </div>
          </div>
      </div>

    </div>
  </div>
</div>