config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'
  get 'revenues_controller/index'
  get 'messages/index'
  get 'conversations/index'
  root 'homes#top'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, except: [:edit]  do
    member do
      get 'profile'
      get 'description'
      get 'favorite_store'
      get 'photo_upload'
      get 'exit'
    end
  end

  resources :plans, except: [:edit] do
    member do
      get 'listing'
      get 'rest_info'
      get 'description'
      get 'photo_upload'
      get 'time_info'
    end
    resources :photos, only: [:update, :destroy]
    resources :reservations, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/your_reservation' => 'reservations#your_reservation'
  get '/your_entry' => 'reservations#your_entry'

  resources :restaurants, only: [:create, :update]
  get '/search_gnabi' => 'restaurants#search_gnabi'

  get 'search' => 'homes#search'
  get 'search_jenre' => 'homes#search_jenre'

  get 'dashboard' => 'dashboards#index'
  resources :revenues, only: [:index]

  get '/payment_method' => "users#payment"
  post '/add_card' => "users#add_card"

  post 'messages' => 'messages#create'
  get '/conversations' => 'conversations#list'
  get '/conversations/:id' => 'conversations#show', as: "conversation_detail"

  get '/about' => "homes#about"
  get '/privacy' => "homes#privacy"
  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
     <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% unless %w[search search_jenre].any? { |name| current_page?(send("#{name}_path")) } %>
	<footer>
		<div class="copyright text-center">
			<p>© 2019 - All Rights Reserved</p>
		</div>
		<div class="sns text-center">
			<a href="#" class="contact">Contact</a>
			<a href="#" class="fb"><i class="fab fa-facebook-square fa-2x"></i></a>
			<a href="#" class="tw"><i class="fab fa-twitter-square fa-2x"></i></a>
			<a href="#" class="insta"><i class="fab fa-instagram fa-2x"></i></a>
		</div>
	</footer>
<% end %>

app/views/shared/_message.html.erb
<% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% key = "success" if key == "notice" %>
          <% key = "error" if key == "alert" %>
          toastr['<%= key %>']('<%= value %>');
        <% end %>
      </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BistMatch", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "どこに行きたい？", class: "form-control" %>
              <i class="fas fa-search" style="color: white;"></i>
            </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-normal btn-small">
            <%= link_to "ホストを始める", new_plan_path, style: "color: white; text-decoration: none;" %>
          </button>
        </li>

        <% if (!user_signed_in?) %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "サイト紹介", about_path %></li>
        <% else %>
            <li>
              <%= link_to notifications_path do %>
                <i class="fas fa-bell fa-2x"></i>
                <span class="badge" id="navbar_num_of_unread"><%= unread_notifications if unread_notifications > 0 %></span>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                    role="button" aria-haspopup="true" aria-expanded="false">
                    <%= attachment_image_tag current_user, :image, :fill, 40, 40, fallback: "no_image.png", size:'40x40', class: "img-circle" %>&nbsp;
                    <%= current_user.fullname %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "管理画面", "/admin" %></li>
                <% end %>
                <li><%= link_to "ダッシュボード", dashboard_path %></li>
                <li><%= link_to "新規プラン作成", new_plan_path %></li>
                <li><%= link_to "ホストプラン一覧", plans_path %></li>
                <li><%= link_to "参加希望一覧", your_reservation_path %></li>
                <li><%= link_to "参加プラン", your_entry_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "マイページ", user_path(current_user) %></li>
                <li><%= link_to "プロフィール編集", profile_user_path(current_user) %></li>
                <li><%= link_to "メッセージ", conversations_path %></li>
                <li><%= link_to "収益管理", revenues_path %></li>
                <li><%= link_to "カード情報", payment_method_path %></li>
                <li><%= link_to "退会ページ", exit_user_path(current_user) %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>