config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'
  get 'revenues_controller/index'
  get 'messages/index'
  get 'conversations/index'
  root 'homes#top'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, except: [:edit]  do
    member do
      get 'profile'
      get 'description'
      get 'favorite_store'
      get 'photo_upload'
      get 'exit'
    end
  end

  resources :plans, except: [:edit] do
    member do
      get 'listing'
      get 'rest_info'
      get 'description'
      get 'photo_upload'
      get 'time_info'
    end
    resources :photos, only: [:update, :destroy]
    resources :reservations, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/your_reservation' => 'reservations#your_reservation'
  get '/your_entry' => 'reservations#your_entry'

  resources :restaurants, only: [:create, :update]
  get '/search_gnabi' => 'restaurants#search_gnabi'

  get 'search' => 'homes#search'
  get 'search_jenre' => 'homes#search_jenre'

  get 'dashboard' => 'dashboards#index'
  resources :revenues, only: [:index]

  get '/payment_method' => "users#payment"
  post '/add_card' => "users#add_card"

  post 'messages' => 'messages#create'
  get '/conversations' => 'conversations#list'
  get '/conversations/:id' => 'conversations#show', as: "conversation_detail"

  get '/about' => "homes#about"
  get '/privacy' => "homes#privacy"
  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @plans = current_user.plans.includes(:restaurant).page(params[:page]).per(6)
    @favoPlans = current_user.favorites.includes(:plan).all
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><%= current_user.fullname %> 様</div>
        <div class="panel-body">
            <div class="image-wrapper">
              <%= attachment_image_tag current_user, :image, :fill, 100, 100, fallback: "no_image.png", size:'100x100', class: "img-circle" %><br/><br/>
            </div>
            <ul class="sidebar-list user-info">
              <li>E-mail: <span class="pull-right icon-babu"><i class="fas fa-envelope"></i></span><%= current_user.email %></li>
              <li>職業: <span class="pull-right icon-babu"><i class="fas fa-user-md"></i></span><%= current_user.job %></li>
              <li>好きなジャンル: <span class="pull-right icon-babu"><i class="fas fa-utensils"></i></span><%= current_user.jenre.name %></li>
              <li>好きなお店: <span class="pull-right icon-babu"><i class="fas fa-utensils"></i></span><%= current_user.favorite_store %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-9">

      <!-- Notification -->
      <div class="panel panel-default">
        <div class="panel-heading">Notifications</div>
        <div class="panel-body">
            <%= link_to notifications_path do %>
                You have <span id="num_of_unread"><%= current_user.unread %></span> notification(s).
            <% end %>
        </div>
      </div>

      <!-- Favorites -->
      <div class="panel panel-default">
        <div class="panel-heading">
          お気に入り一覧
        </div>
        <div class="panel-body">

          <% @favoPlans.each do |f| %>
            <div class="row">
              <div class="col-md-2">
                <%= f.plan.plan_date %>
              </div>
              <div class="col-md-2">
                <%= link_to plan_path(f.plan) do %>
                  <% if f.plan.restaurant.image_url.present? %>
                    <%= image_tag "#{f.plan.restaurant.image_url}", size: '100x100'  %>
                  <% else %>
                    <%= attachment_image_tag f.plan.photos[0], :image, :fill, 100, 100 %>
                  <% end %>
                <% end %>
              </div>
              <div class="col-md-5">
                <%= link_to f.plan.title, plan_path(f.plan) %><br/><br/>
                <span>
                  <%= attachment_image_tag f.plan.user, :image, :fill, 40, 40, fallback: "no_image.png", size:'40x40', class: "img-circle" %>
                  <%= link_to user_path(f.plan.user) do %>
                      <%= f.plan.user.fullname %>
                  <% end %>
                </span>
              </div>
              <div class="col-md-2">
                <%= f.plan.status %>
              </div>
            </div>
            <hr/>
          <% end %>
        </div>
      </div>

      <!-- Your Plans -->
      <h4 class="row-space-3">ホストプラン一覧 (<%= @plans.length %>)</h4>
      <div class="row">
        <%= render partial: "plans/plan_list", locals: {plans: @plans} %>
      </div>

    </div>
  </div>
</div>