config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'notifications/index'
  get 'revenues_controller/index'
  get 'messages/index'
  get 'conversations/index'
  root 'homes#top'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, except: [:edit]  do
    member do
      get 'profile'
      get 'description'
      get 'favorite_store'
      get 'photo_upload'
      get 'exit'
    end
  end

  resources :plans, except: [:edit] do
    member do
      get 'listing'
      get 'rest_info'
      get 'description'
      get 'photo_upload'
      get 'time_info'
    end
    resources :photos, only: [:update, :destroy]
    resources :reservations, only: [:create]
    resource :favorites, only: [:create, :destroy]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/your_reservation' => 'reservations#your_reservation'
  get '/your_entry' => 'reservations#your_entry'

  resources :restaurants, only: [:create, :update]
  get '/search_gnabi' => 'restaurants#search_gnabi'

  get 'search' => 'homes#search'
  get 'search_jenre' => 'homes#search_jenre'

  get 'dashboard' => 'dashboards#index'
  resources :revenues, only: [:index]

  get '/payment_method' => "users#payment"
  post '/add_card' => "users#add_card"

  post 'messages' => 'messages#create'
  get '/conversations' => 'conversations#list'
  get '/conversations/:id' => 'conversations#show', as: "conversation_detail"

  get '/about' => "homes#about"
  get '/privacy' => "homes#privacy"
  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

end

app/models/plan.rb
class Plan < ApplicationRecord
  enum status: { 募集終了: 0, 募集中: 1 }
  enum period_time: { 朝: 0, ランチタイム: 1, 夕方・夜: 2 }

  has_many :reservations, dependent: :destroy
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, attachment: :image

  has_many :guest_reviews
  has_many :favorites, dependent: :destroy

  belongs_to :user
  belongs_to :restaurant
  belongs_to :jenre
  belongs_to :area

  geocoded_by :address

  validates :title, presence: true, length: { maximum: 40 }
  validates :latitude, presence: true
  validates :longitude, presence: true

  # 募集中の利用可能なプランを取得
  scope :available, lambda {
    where('status = ? AND active = ?', 1, true)
  }

  # プランにいいね
  def good(user)
    favorites.create(user_id: user.id)
  end

  # いいねを取り消す
  def ungood(user)
    favorites.find_by(user_id: user.id).destroy
  end

  # いいね済みかどうか確認
  def good?(user)
    user_ids = favorites.pluck(:user_id)
    user_ids.include?(user.id)
  end

  # プランに必要なrestaurantの情報を追加する
  def add_restinfo(rest)
    self.restaurant_id = rest.id
    self.latitude = rest.latitude
    self.longitude = rest.longitude
  end

  # レビューの平均点の取得
  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

  # プランの入力情報があるか確認
  def is_ready_plan?
    !active && price.present? && member.present? && jenre_id.present? && status.present? && area_id.present? &&
      restaurant.name.present? && restaurant.address.present? && restaurant.line.present? && restaurant.station.present? &&
      restaurant.walk.present? && summary.present? && title.present? && requirement.present? && photos.present? &&
      plan_date.present? && start_time.present? && end_time.present? && deadline.present?
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action  :set_plan, except: %i[new index create]
  before_action  :set_rest, only: %i[new create]
  before_action  :authenticate_user!, except: [:show]
  before_action  :correct_user, only: %i[listing rest_info photo_upload description time_info update]

  def index
    @plans = Plan.includes(:restaurant).where(user_id: current_user.id).order(id: :asc).page(params[:page]).per(10)
  end

  def new
    @plan = current_user.plans.build
  end

  def create
    @plan = current_user.plans.build(plan_params)
    @plan.add_restinfo(@restaurant)
    if @plan.save
      redirect_to listing_plan_path(@plan), notice: 'プランを新規作成しました！'
    else
      flash.now[:alert] = 'プランの新規作成に失敗しました'
      render :new
    end
  end

  def show
    @photos = @plan.photos
    @guest_reviews = @plan.guest_reviews.page(params[:page]).per(4)
  end

  def rest_info
    @restaurant = Restaurant.find_by(id: @plan.restaurant_id)
  end

  def photo_upload
    @photos = @plan.photos
  end

  def update
    new_params = plan_params
    new_params = plan_params.merge(active: true) if @plan.is_ready_plan?

    if @plan.update(new_params)
      if @plan.active == true
        return redirect_to plan_path(@plan), notice: 'プランを公開しました！'
      end

      flash[:notice] = '編集内容を保存しました！'
    else
      flash[:alert] = '編集内容の保存に失敗しました...'
    end
    redirect_back(fallback_location: request.referer)
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_rest
    @restaurant = Restaurant.where(user_id: current_user.id).last
    redirect_to search_gnabi_path, notice: '店舗情報をまず登録してください' if @restaurant.nil?
  end

  # 正しいユーザーか確認する
  def correct_user
    unless current_user.id == @plan.user.id
      redirect_to root_path, alert: '権限がありません..'
      end
  end

  def plan_params
    params.require(:plan).permit(:title, :summary, :restaurant_id, :price, :member, :start_time, :end_time, :plan_date,
                                 :deadline, :requirement, :jenre_id, :user_id, :area_id, :period_time, :status, :is_holiday, :active)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_plan_list.html.erb
<% plans.each do |plan| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <% if plan.restaurant.image_url.present? %>
            <%= image_tag "#{plan.restaurant.image_url}", size: '200x200'  %>
          <% else %>
            <%= attachment_image_tag plan.photos[0], :image, size: '200x200' %>
          <% end %>
        </div>
        <div class="panel-body text-adjust">
          <%= link_to plan.title, plan %><br/>
          <div class="info">
            ¥<%= plan.price %>&nbsp;&nbsp;
            <%= plan.status %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/plans/_plan_menu.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      登録情報リスト
  </div>

  <div class="panel-body">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "プラン情報", listing_plan_path, class: "sidebar-link active" %>
        <% if !@plan.price.blank? && !@plan.member.blank? && !@plan.jenre_id.blank? && !@plan.status.blank? && !@plan.area_id.blank? %>
          <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "プラン店舗情報", rest_info_plan_path, class: "sidebar-link active" %>
        <% if !@plan.restaurant.name.blank? && !@plan.restaurant.address.blank? && !@plan.restaurant.line.blank? && !@plan.restaurant.station.blank? && !@plan.restaurant.walk.blank? %>
          <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "プラン紹介", description_plan_path, class: "sidebar-link active" %>
        <% if !@plan.summary.blank? && !@plan.title.blank? && !@plan.requirement.blank? %>
          <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "イメージ画像", photo_upload_plan_path, class: "sidebar-link active" %>
        <% if !@plan.photos.blank? %>
          <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
      <li class="sidebar-item">
        <%= link_to "プラン日時", time_info_plan_path, class: "sidebar-link active" %>
        <% if !@plan.plan_date.blank? && !@plan.start_time.blank? && !@plan.end_time.blank? && !@plan.deadline.blank? %>
          <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

<hr/>

<% is_ready = !@plan.active && !@plan.price.blank? && !@plan.member.blank? && !@plan.jenre_id.blank? && !@plan.status.blank? && !@plan.area_id.blank? &&
               !@plan.restaurant.name.blank? && !@plan.restaurant.address.blank? && !@plan.restaurant.line.blank? && !@plan.restaurant.station.blank? &&
               !@plan.restaurant.walk.blank? && !@plan.summary.blank? && !@plan.title.blank? && !@plan.requirement.blank? && !@plan.photos.blank? &&
               !@plan.plan_date.blank? && !@plan.start_time.blank? && !@plan.end_time.blank? && !@plan.deadline.blank?
%>


<% if @plan.active == false %>
  <%= form_for @plan do |f| %>
    <%= f.hidden_field :active, value: true %>
    <%= f.submit "プランを公開する", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
  <% end %>
<% else %>
  <%= link_to "プランの詳細へ行く", plan_path(@plan), class: "btn btn-normal btn-block" %>
<% end %>

app/views/plans/description.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'plan_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          プラン紹介
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @plan do |f| %>

            <div class="row">
                <div class="form-group">
                  <label>タイトル</label>
                  <%= f.text_field :title, placeholder: "プランのタイトルを入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>プラン紹介</label>
                  <%= f.text_area :summary, rows: 7,  placeholder: "プラン紹介コメントを入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>参加条件・注意事項</label>
                  <%= f.text_area :requirement, rows: 7,  placeholder: "参加条件・注意事項を入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "保存", class: "btn btn-form" %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<div class="container row-space-6 bottom-space">
  <div class="row">
    <div class="col-md-3">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "ホストプラン一覧", plans_path, class: "sidebar-link active" %></li>
        <li class="sidebar-item"><%= link_to "参加希望一覧", your_reservation_path, class: "sidebar-link" %></li>
        <li class="sidebar-item"><%= link_to "参加プラン一覧", your_entry_path, class: "sidebar-link" %></li>
      </ul>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          ホストプラン一覧
        </div>
        <div class="panel-body">

          <% @plans.each do |plan| %>
            <div class="row">
              <div class="col-md-2">
                <%= plan.plan_date %>
              </div>
              <div class="col-md-2">
                <% if plan.restaurant.image_url.present? %>
                  <%= image_tag "#{plan.restaurant.image_url}", size: '100x100'  %>
                <% else %>
                  <%= attachment_image_tag plan.photos[0], :image, :fill, 100, 100 %>
                <% end %>
              </div>
              <div class="col-md-5">
                <h4><%= plan.title %></h4>
              </div>
              <div class="col-md-3 right">
                <%= link_to "編集する", listing_plan_path(plan), class: "btn btn-normal" %>
                <p class="row-space-2"><%= plan.status %></p>
              </div>
            </div>
            <hr/>
          <% end %>
          <%= paginate @plans, class: "paginate" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/listing.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'plan_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          プラン情報
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @plan do |f| %>

              <div class="row">

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>料金（ホストへのFee）</label>
                    <%= f.text_field :price, placeholder: "eg ¥1000 半角数字で料金を入力...", class: "form-control", required: true %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>参加受付人数</label>
                    <%= f.select :member, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30], class: "form-control" %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>募集プランのジャンル</label>
                    <%= f.collection_select :jenre_id, Jenre.all, :id, :name, :prompt => "選択して下さい", class: 'form-control' %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>募集プランのエリア</label>
                    <%= f.collection_select :area_id, Area.all, :id, :name, :prompt => "選択して下さい", class: 'form-control' %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>募集ステータス</label>
                    <%= f.select :status, Plan.statuses.keys.to_a, {} %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>プランの祝休日情報</label>
                    <%= f.select :is_holiday, [["当てはまらない", 0], ["当てはまる", 1]], selected: "当てはまらない",
                                  id: "holiday", prompt: "選択して下さい", class: "form-control" %>
                  </div>
                </div>

                <div class="col-md-6 select">
                  <div class="form-group">
                    <label>時間帯</label>
                      <%= f.select :period_time, Plan.period_times.keys.to_a, {} %>
                  </div>
                </div>

              </div>

              <div class="text-center">
                <%= f.submit "保存", class: "btn btn-form" %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/plans/new.html.erb
<div class="container row-space-4">
  <h2>新規プラン作成</h2>
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        現在のプラン登録店舗情報
      </div>

      <div class="panel-body">
        <div class="col-md-offset-2 col-md-4">
        <% if @restaurant.present? && @restaurant.image_url.present? %>
          <%= image_tag "#{@restaurant.image_url}", size: '200x200'  %>
        <% else %>
          <%= image_tag 'default_image.png', size: '200x200' %>
        <% end %>
        </div>

        <div class="col-md-6">
          <% if @restaurant.present? %>
            <h4>店名<h4><br>
            <p><%= @restaurant.name %></p><br>
            <h4>住所</h4><br>
            <p><%= @restaurant.address %></p>
          <% else %>
            <h3>登録情報はありません</h3>
          <% end %>
          <hr>

          <%= link_to "プランに合うお店を探す", search_gnabi_path, class: "btn btn-normal" %>

          <br><br>

          <%= form_for @plan do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <label>タイトル</label>
            <%= f.text_field :title, placeholder: "プランのタイトルを入力...", class: "form-control" %>
            <br>
            <%= button_tag type: "submit", class: "btn btn-form"  do %>
              <i>この店舗でプランを新規作成する</i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/photo_upload.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'plan_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          画像アップロード
        </div>

        <div class="panel-body">
          <div class="container">
            <div class="row">
              <div class="col-md-offset-3 col-md-6">
                <!-- PHOTOS UPLOAD GOES HERE -->

                <%= form_for @plan, url: plan_photo_path(@plan), method: :patch do |f| %>
                  <div class="row">
                    <div class="form-group">
                      <span class="btn btn-default btn-file text-babu">
                        <i class="fas fa-cloud-upload" aria-hidden="true"></i> 画像を選ぶ
                        <%= f.attachment_field :photos_images, multiple: true, class: 'form-control' %>
                      </span>
                    </div>
                  </div>

                  <div class="text-center">
                    <%= f.submit "選択画像を追加", class: "btn btn-form" %>
                  </div>

                <% end %>
              </div>
            </div>

            <div id="photos"><%= render 'photos/photos_list' %></div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/plans/rest_info.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'plan_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          プラン開催店舗情報
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @restaurant do |f| %>

            <div class="row">
                <div class="form-group">
                  <label>店名</label>
                  <%= f.text_field :name, placeholder: "店名を入力...", class: "form-control", required: true %>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <label>住所</label>
                  <%= f.text_area :address, rows: 3,  placeholder: "住所を入力...", class: "form-control", required: true %>
                </div>
              </div>


              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>平均予算</label>
                    <%= f.text_field :budget, placeholder: "平均予算を入力...", class: "form-control", required: true %>
                  </div>
                </div>


                <div class="col-md-6">
                  <div class="form-group">
                    <label>最寄駅の路線</label>
                    <%= f.text_field :line, placeholder: "最寄り駅の路線を入力...", class: "form-control", required: true %>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>最寄駅</label>
                    <%= f.text_field :station, placeholder: "最寄り駅を入力...", class: "form-control", required: true %>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label>駅からの徒歩距離(分)</label>
                    <%= f.number_field :walk, min:1 ,max:60, class: "form-control", required: true %>
                  </div>
                </div>
              </div>



              <div class="text-center">
                <%= f.submit "保存", class: "btn btn-form" %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="container">
  <!-- Image -->
  <div class="row">
    <div class="col-md-12">
      <%= attachment_image_tag @photos[0], :image, :fill, 1000, 500, fallback: "no_image.png", class: 'image_size' %>
    </div>
  </div>
  <br/>


  <div class="row">


    <!-- LEFT AREA -->
    <div class="col-md-8">

      <!-- Host Info -->
      <div class="row">
        <div class="col-md-8">
          <h1><%= @plan.title %></h1>
          <ul class="cp_tag01">
            <li><p class="btn-border side-space-1"><%= @plan.status %></p></li>
            <li><a href="#"><%= @plan.jenre.name %></a></li>
            <li><a href="#"><%= @plan.area.name %></a></li>
          </ul>
          <!-- Favorite icon -->
          <div class = "plan_favorite">
            <% if user_signed_in? %>
              <%= render "favorites/favorite", plan: @plan %>
            <% else %>
              <span class="favo">
                <i class="far fa-heart fa-2x" aria-hidden="true" style="color: red"></i>
                <%= content_tag :span, "#{@plan.favorites_count}", style: 'color: red' %>
              </span>
            <% end %>
          </div>

        </div>
        <div class="col-md-4 text-center">
          <%= link_to user_path(@plan.user) do %>
            <%= attachment_image_tag @plan.user, :image, :fill, 100, 100, fallback: "no_image.png", size:'100x100', class: "img-circle" %><br/><br/>
            <%= @plan.user.fullname %>
          <% end %>
        </div>
      </div>
      <hr/>

      <!-- About the plan -->
      <div class="row">
        <div class="col-md-12">
          <h3>このプランについて</h3>
          <p><%= @plan.summary %></p>
        </div>
      </div>
      <hr/>

      <!-- Plan info -->
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-5">
              <ul class="plan-info">
                <li>日時: <%= @plan.plan_date %></li>
                <li>開催時間: <%= "#{@plan.start_time.strftime("%R")} ~ #{@plan.end_time.strftime("%R")}" %></li>
                <li>開催場所: <%= @plan.restaurant.name %></li>
                <li>募集人数: <%= @plan.member %>人</li>
                <li>料金(Host Fee): <%= @plan.price.to_s(:delimited) %>円</li>
                <li>平均予算: <%= @plan.restaurant.budget.to_s(:delimited) %>円</li>
              </ul>
            </div>
            <div class="col-md-7">
              <ul class="plan-info">
                <li>申込期限: <%= @plan.deadline %>の23:59まで (期限内に参加希望必須)</li>
                <li>プランへの参加条件・注意事項:<br/> <%= @plan.requirement  %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <hr/>

      <!-- Slideshow -->
      <div class="row">

        <% if @photos.length > 0 %>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">

            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                  <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>

            <div class="carousel-inner">
              <% @photos.each do |photo| %>
                  <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                    <%= attachment_image_tag photo, :image, fallback: "no_image.png", class: 'image_size' %>
                  </div>
              <% end %>
            </div>

            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% end %>

      </div>
      <hr/>

      <!-- REVIEWS -->
      <div class="row">
        <div class="col-md-12">
          <h3>
            <%= pluralize(@guest_reviews.count, "Review") %>
            <span id="average_rating"></span>
          </h3>
          <div class="container">
            <div><%= render "reviews/guest_list" %></div>
          </div>
        </div>
      </div>
      <br/>
      <hr/>

      <!-- GOOGLE MAP -->
      <div class="row">
        <h3>店舗情報</h3>
        <ul class="plan-info">
          <li><a href="<%= @plan.restaurant.pc_url %>"><%= @plan.restaurant.name %></a></li>
          <li><%= @plan.restaurant.address %></li>
          <li><%= @plan.restaurant.line %><%= @plan.restaurant.station %>から徒歩<%= @plan.restaurant.walk %>分</li>
        </ul>
        <div id="map" style="width: 100%; height: 400px"></div>

        <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API_KEY'] %>&language=ja&callback=initialize" async defer></script>
        <script>
            function initialize() {
              var location = {lat: <%= @plan.restaurant.latitude %>, lng: <%= @plan.restaurant.longitude %>};
              var map = new google.maps.Map(document.getElementById('map'), {
                center: location,
                zoom: 14
              });

              var marker = new google.maps.Marker({
                position: location,
                map: map
              });

              var infoWindow = new google.maps.InfoWindow({
                content: '<div id="content"><%= image_tag @plan.restaurant.image_url %></div><div id="content"><%= @plan.restaurant.name %></div>'
              });

              infoWindow.open(map, marker);
            }

            google.maps.event.addDomListener(window, 'load', initialize);
        </script>

      </div>
      <hr/>

      <!-- NEAR BY PLANS -->
      <div class="row">
        <h3>近くで募集中のプラン</h3><br>
        <% @plan.restaurant.nearbys(3).each do |rest| %>
          <% if Plan.exists?(restaurant_id: rest.id, status: 1) %>
            <% rest.plans.each do |plan| %>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading preview">
                  <%= link_to plan do %>
                    <% if rest.image_url.present? %>
                      <%= image_tag "#{rest.image_url}", size: '200x200'  %>
                    <% else %>
                      <%= attachment_image_tag plan.photos[0], :image, size: '200x200' %>
                    <% end %>
                  <% end %>
                  </div>
                  <div class="panel-body text-adjust">
                    <%= link_to plan.title, plan %><br/>
                    <div class="info">
                      ¥<%= plan.price %>&nbsp;&nbsp;
                      <%= plan.status %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- RIGHT AREA -->
    <div class="col-md-4">
      <!-- Reservation Form -->
      <%= render 'reservations/form' %>
    </div>
  </div>

  </div>
</div>

<script>
  $('#average_rating').raty({
    starOff: '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    readOnly: true,
    score: <%= @plan.average_rating %>
  });
</script>

app/views/plans/time_info.html.erb
<div class="container row-space-4">
  <div class="row">
    <div class="col-md-3">
      <%= render 'plan_menu' %>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          プラン日時
        </div>

        <div class="panel-body">
          <div class="container">
            <%= form_for @plan do |f| %>

              <div class="row">
                    <div class="col-md-offset-1 col-md-6">
                      <div class="form-group row-space-3">
                        <label>実施日</label>
                        <%= f.text_field :plan_date, autocomplete: 'off', class: 'form-control', id: 'plan_date' %>
                      </div>
                    </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="time-group">
                      <label>開始時間</label>
                      <%=  f.time_select :start_time, include_blank: true, ignore_data: true,  minute_step: 15, class: 'time-box form-control' %>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="time-group">
                      <label>終了時間</label>
                      <%=  f.time_select :end_time, include_blank: true, ignore_data: true, minute_step: 15, class: 'time-box form-control' %>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-offset-1 col-md-6">
                      <div class="form-group row-space-3">
                        <label>募集の締切日</label>
                        <%= f.text_field :deadline, autocomplete: 'off', class: 'form-control', id: 'deadline' %>
                      </div>
                  </div>
                  <div class="col-md-5 row-space-4">
                    <p>指定締切日の23:59までの期間で募集を行います</p>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "保存", class: "btn btn-form text-center" %>
                </div>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<script>
  $(function(){

      $('#plan_date').datepicker({
        dateFormat: 'yy-mm-dd',
        minDate: 0,
        maxDate: '3m',
      });

      $('#deadline').datepicker({
        dateFormat: 'yy-mm-dd',
        minDate: 0,
        maxDate: '3m',
      });
    });

</script>